[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "no-redzone",
    "-C", "target-feature=-mmx,-sse,-sse2",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
