[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "no-redzone",
    "-C", "target-feature=-mmx,-sse,-sse2",
]

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
